<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Support\Facades\Auth;

class StoreTicketRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        // Authorization logic: Must be an 'employer'.
        return Auth::check() && Auth::user()->hasRole('employer');
    }

    /**
     * Get the validation rules that apply to the request.
     */
    public function rules(): array
    {
        return [
            'subject' => ['required', 'string', 'max:255'],
            // Initial message is optional (nullable).
            'message' => ['nullable', 'string', 'max:5000'],
            // Validation for data submitted via dynamic hidden inputs (generated by Alpine.js)
            // These will be submitted as standard form arrays.
            'attachments' => ['nullable', 'array'],
            'attachments.existing_employees' => ['nullable', 'array'],
            'attachments.new_employees' => ['nullable', 'array'],
            // File uploads will be handled separately.
        ];
    }
}
