@extends('layouts.app')

{{-- Determine the correct context and prepare data --}}
@php
    $isAdminView = request()->routeIs('admin.tickets.*');
    $viewTitle = $isAdminView ? 'จัดการตั๋วงาน' : 'รายละเอียดคำขอ';

    // Helper function for file size formatting (defined here as it's not globally available)
    if (!function_exists('formatBytes')) {
        function formatBytes($bytes, $precision = 2) {
            $units = array('B', 'KB', 'MB', 'GB', 'TB');
            $bytes = max($bytes, 0);
            $pow = floor(($bytes ? log($bytes) : 0) / log(1024));
            $pow = min($pow, count($units) - 1);

            // Check if $pow is 0 to handle very small file sizes correctly
            if ($pow == 0) {
                return round($bytes, $precision) . ' ' . $units[$pow];
            }

            $bytes /= pow(1024, $pow);
            return round($bytes, $precision) . ' ' . $units[$pow];
        }
    }

    // Access the pre-processed attachments via the accessor
    $attachments = $ticket->categorized_attachments;
@endphp

@section('title', $viewTitle . ' #' . $ticket->id)

@section('content')
<div class="content-section">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h2>{{ $ticket->subject }}</h2>
        {{-- Display Status Badge --}}
        <span class="badge bg-{{ $ticket->status_color }} fs-5">
            {{ $ticket->status_name }}
        </span>
    </div>

    <div class="row">
        {{-- Column 1: Main Content (Triage, History, Reply) --}}
        <div class="col-lg-8">

            {{-- Section 1: Triage (Attachments Summary) --}}
            @if($attachments->existing_employees->isNotEmpty() || $attachments->new_employees->isNotEmpty() || $attachments->files->isNotEmpty())
            <div class="card mb-4 border-info">
                <div class="card-header bg-info text-white">
                    <h5 class="mb-0"><i class="bi bi-paperclip me-2"></i>สิ่งที่แนบมา (Attachments Triage)</h5>
                </div>
                <div class="card-body">

                    {{-- 1.1 Existing Employees --}}
                    @if($attachments->existing_employees->isNotEmpty())
                        <h6 class="text-primary mt-3">ลูกจ้างที่มีอยู่ ({{ $attachments->existing_employees->count() }} คน)</h6>
                        <div class="list-group mb-3">
                            @foreach($attachments->existing_employees as $employee)
                                <div class="list-group-item d-flex align-items-center gap-3 py-2">
                                    <img src="{{ $employee->photo_url }}" alt="Photo" class="rounded-circle" style="width: 40px; height: 40px; object-fit: cover;">
                                    <span class="flex-grow-1">
                                        <strong>{{ $employee->employeeNameTh }}</strong>
                                        <small class="text-muted">({{ $employee->employeePassport }})</small>
                                    </span>
                                    {{-- V2.4-S9: Historical Integrity Check --}}
                                    @if($employee->trashed())
                                        <span class="badge bg-danger me-2">ลบ/จำหน่ายแล้ว</span>
                                    @endif
                                    {{-- Link to employee detail page (if user has permission) --}}
                                    @can('view-employees')
                                        {{-- Use $employee->id explicitly as withTrashed might affect route model binding --}}
                                        <a href="{{ route('employees.show', $employee->id) }}" target="_blank" class="ms-auto btn btn-sm btn-outline-secondary">ดูข้อมูล</a>
                                    @endcan
                                </div>
                            @endforeach
                        </div>
                    @endif

                    {{-- 1.2 New Employees --}}
                    @if($attachments->new_employees->isNotEmpty())
                        <h6 class="text-success mt-3">ลูกจ้างใหม่/แจ้งเข้า ({{ $attachments->new_employees->count() }} คน)</h6>
                        <div class="list-group mb-3">
                            @foreach($attachments->new_employees as $newEmployee)
                                <div class="list-group-item py-2">
                                    <strong>{{ $newEmployee->employeeTitleTh ?? '' }}{{ $newEmployee->employeeNameTh }}</strong>
                                    <small class="text-muted">({{ $newEmployee->employeePassport }})</small>
                                    {{-- Display links to uploaded files (using URLs generated by the accessor) --}}
                                    <div class="mt-2 d-flex gap-2 flex-wrap">
                                        @if(isset($newEmployee->employeePhoto_url))
                                            <a href="{{ $newEmployee->employeePhoto_url }}" target="_blank" class="btn btn-sm btn-outline-info">รูปถ่าย</a>
                                        @endif
                                        @if(isset($newEmployee->document_1_url))
                                            <a href="{{ $newEmployee->document_1_url }}" target="_blank" class="btn btn-sm btn-outline-info">เอกสาร 1</a>
                                        @endif
                                    </div>
                                </div>
                            @endforeach
                        </div>
                    @endif

                    {{-- 1.3 General Files --}}
                    @if($attachments->files->isNotEmpty())
                        <h6 class="text-secondary mt-3">ไฟล์แนบทั่วไป ({{ $attachments->files->count() }} ไฟล์)</h6>
                        <div class="list-group mb-3">
                            @foreach($attachments->files as $file)
                                @if($file->url)
                                    <a href="{{ $file->url }}" target="_blank" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center py-2">
                                        <span><i class="bi bi-file-earmark-text me-2"></i> {{ $file->name }}</span>
                                        <small class="text-muted">{{ formatBytes($file->size) }}</small>
                                    </a>
                                @else
                                    <div class="list-group-item list-group-item-action d-flex justify-content-between align-items-center py-2 text-danger">
                                        <span><i class="bi bi-exclamation-triangle me-2"></i> {{ $file->name }} (ไฟล์สูญหาย)</span>
                                    </div>
                                @endif
                            @endforeach
                        </div>
                    @endif
                </div>
            </div>
            @endif
            {{-- End Section 1: Triage --}}


            {{-- Section 2: Communication History (Chat View) --}}
            <div class="card mb-4">
                <div class="card-header">
                    <h5 class="mb-0"><i class="bi bi-chat-left-text me-2"></i>ประวัติการสนทนา</h5>
                </div>
                <div class="card-body" style="max-height: 500px; overflow-y: auto;">
                    @php $hasConversation = false; @endphp
                    {{-- Messages are already sorted chronologically by the Controller --}}
                    @foreach($ticket->messages as $message)
                        {{-- Display only 'comment' and 'system_activity' types in the main chat history --}}
                        @if($message->message_type == 'comment')
                            @php $hasConversation = true; @endphp
                            <div class="d-flex mb-3">
                                <div class="flex-shrink-0 me-3">
                                    {{-- Placeholder Avatar --}}
                                    <i class="bi bi-person-circle fs-2 text-muted"></i>
                                </div>
                                <div class="flex-grow-1">
                                    <div class="d-flex justify-content-between align-items-center">
                                        <strong>{{ $message->user->name ?? 'ผู้ใช้งาน (ลบแล้ว)' }}</strong>
                                        <small class="text-muted">{{ $message->created_at->format('d M Y H:i') }}</small>
                                    </div>
                                    <div class="p-3 rounded" style="background-color: #f1f5f9;">
                                        {{-- Use nl2br to respect line breaks in the message body --}}
                                        {!! nl2br(e($message->body)) !!}
                                    </div>
                                </div>
                            </div>
                            <hr>
                        @elseif($message->message_type == 'system_activity')
                             @php $hasConversation = true; @endphp
                            {{-- Future implementation for system logs --}}
                             <div class="text-center my-3">
                                 <span class="badge bg-secondary">{{ $message->body }} - {{ $message->created_at->format('H:i') }}</span>
                             </div>
                             <hr>
                        @endif
                    @endforeach

                    @if(!$hasConversation)
                        <p class="text-center text-muted py-4">ยังไม่มีการสนทนา</p>
                    @endif
                </div>
            </div>
            {{-- End Section 2: Communication History --}}


            {{-- Section 3: Reply Box (Placeholder for V2.4-S10) --}}
            <div class="card">
                <div class="card-body">
                    <h5 class="mb-3">ตอบกลับ</h5>
                    <textarea class="form-control" rows="4" placeholder="พิมพ์ข้อความตอบกลับ (V2.4-S10 Placeholder)" disabled></textarea>
                    <button class="btn btn-primary mt-3" disabled>ส่งข้อความ</button>
                </div>
            </div>
            {{-- End Section 3: Reply Box --}}
        </div>

        {{-- Column 2: Metadata Sidebar --}}
        <div class="col-lg-4">
            <div class="card sticky-top" style="top: 20px;">
                <div class="card-header">
                    <h5 class="mb-0">ข้อมูลตั๋วงาน</h5>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <strong>Ticket ID:</strong> #{{ $ticket->id }}
                    </li>
                    <li class="list-group-item">
                        <strong>สร้างเมื่อ:</strong> {{ $ticket->created_at->format('d M Y H:i') }}
                    </li>
                     <li class="list-group-item">
                        <strong>อัปเดตล่าสุด:</strong> {{ $ticket->updated_at->format('d M Y H:i') }}
                    </li>
                    {{-- Show Employer Info (More detailed in Admin view) --}}
                    <li class="list-group-item">
                        <strong>ผู้ส่งคำขอ:</strong>
                        @if($isAdminView && $ticket->employerUser)
                             {{-- Eager loaded in Admin Controller --}}
                            {{ $ticket->employerUser->employer->employerNameTh ?? '' }} ({{ $ticket->employerUser->name }})
                        @elseif($ticket->employerUser)
                            {{ $ticket->employerUser->name }}
                        @else
                            N/A (ผู้ใช้งานถูกลบ)
                        @endif
                    </li>
                    {{-- Show Assigned Staff --}}
                    <li class="list-group-item">
                        <strong>ผู้รับผิดชอบ:</strong>
                        {{ $ticket->assignedStaff->name ?? ($isAdminView ? 'ยังไม่ได้มอบหมาย' : 'รอเจ้าหน้าที่รับเรื่อง') }}
                    </li>
                </ul>
                {{-- Admin Action Buttons (Placeholder for V2.4-S11) --}}
                @if($isAdminView)
                    <div class="card-body d-grid gap-2">
                         <h5 class="mb-3">การจัดการ (Admin/Staff)</h5>
                        <button class="btn btn-outline-success" disabled>Mark as Resolved (V2.4-S11)</button>
                        <button class="btn btn-outline-danger" disabled>Reject Ticket (V2.4-S11)</button>
                        <button class="btn btn-outline-primary" disabled>Forward to P-Workflow (V2.4-S11)</button>
                         <button class="btn btn-outline-secondary" disabled>Change Assignment (V2.4-S11)</button>
                    </div>
                @endif
            </div>
        </div>
    </div>
</div>
@endsection
