<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // Delete employers that don't have a user associated with them.
        // These are assumed to be test data generated by seeders like StabilityTestSeeder.
        // Using DB facade to perform a hard delete, relying on ON DELETE CASCADE for employees.
        if (Schema::hasColumn('employers', 'user_id')) {
             DB::table('employers')->whereNull('user_id')->delete();
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        // This operation is destructive and cannot be reversed.
    }
};
