<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\MorphTo;
use Illuminate\Database\Eloquent\SoftDeletes;

class LaborBookTransaction extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'labor_book_account_id',
        'type',
        'category',
        'labor_charge_type_id',
        'labor_expense_category_id',
        'amount',
        'quantity',
        'transaction_date',
        'description',
        'attachment_path',
        'source_type',
        'source_id',
        'created_by',
    ];

    protected $casts = [
        'amount' => 'decimal:2',
        'transaction_date' => 'date',
    ];

    public function account()
    {
        return $this->belongsTo(LaborBookAccount::class, 'labor_book_account_id');
    }

    public function creator()
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    public function source(): MorphTo
    {
        return $this->morphTo();
    }

    public function chargeType()
    {
        return $this->belongsTo(LaborChargeType::class, 'labor_charge_type_id');
    }

    public function expenseCategory()
    {
        return $this->belongsTo(LaborExpenseCategory::class, 'labor_expense_category_id');
    }

    /**
     * Auto-generated rows (e.g. from a team's LaborBillPayment) are not
     * editable/deletable from the books UI — only viewable — to keep them
     * from drifting out of sync with whatever created them.
     */
    public function isAutoGenerated(): bool
    {
        return (bool) $this->source_type;
    }

    /**
     * Single place to resolve a display label for a transaction's
     * category — income rows point at a LaborChargeType, expense rows at
     * a LaborExpenseCategory, except the 'team_payment' auto-link rows
     * (a bill can span multiple charge types, so those don't pick one).
     */
    public function getCategoryLabelAttribute(): string
    {
        if ($this->category === 'team_payment') {
            return 'ชำระค่าบริการจากทีม (อัตโนมัติ)';
        }

        if ($this->type === 'income') {
            return $this->chargeType?->name ?? '-';
        }

        return $this->expenseCategory?->name ?? '-';
    }
}
