<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\MorphTo;
use Illuminate\Database\Eloquent\SoftDeletes;

class LaborBookTransaction extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'labor_book_account_id',
        'type',
        'category',
        'amount',
        'transaction_date',
        'description',
        'source_type',
        'source_id',
        'created_by',
    ];

    protected $casts = [
        'amount' => 'decimal:2',
        'transaction_date' => 'date',
    ];

    public function account()
    {
        return $this->belongsTo(LaborBookAccount::class, 'labor_book_account_id');
    }

    public function creator()
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    public function source(): MorphTo
    {
        return $this->morphTo();
    }

    /**
     * Auto-generated rows (e.g. from a team's LaborBillPayment) are not
     * editable/deletable from the books UI — only viewable — to keep them
     * from drifting out of sync with whatever created them.
     */
    public function isAutoGenerated(): bool
    {
        return (bool) $this->source_type;
    }
}
